# Generated by Django 4.0.1 on 2022-01-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('uom', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_text', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipe_title', models.CharField(max_length=255)),
                ('recipe_subtitle', models.CharField(max_length=255)),
                ('yield_amount', models.IntegerField(default=1)),
                ('yield_type', models.CharField(max_length=128)),
                ('ingredients', models.ManyToManyField(to='recipe.Ingredients')),
            ],
        ),
    ]
